version: '3.7'

services:
  mysql:
    container_name: mysql-db
    env_file:
      - ./backend/.env.development
    image: mysql:8.0
    ports:
      - 3306:3306
    restart: always

  redis:
    container_name: redis-db
    image: redis:alpine
    ports:
      - 6379:6379
    restart: always

  backend:
    container_name: nodejs-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - 5001:5001
    volumes:
      - ./backend/src:/usr/src/app/src
      - /usr/src/app/node_modules
    depends_on:
      - mysql
      - redis

  frontend:
    container_name: react-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true
