version: '3.7'

services:
  db:
    env_file:
      - ./backend/.env.development
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - 3306:3306
    restart: always

  backend:
    container_name: nodejs-backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile.backend
    ports:
      - 5001:5001
    volumes:
      - ./backend:/usr/src/app/backend
    depends_on:
      - db
