type: object
properties:
  id:
    type: integer
    example: 10
  title:
    type: string
    example: 아티클 제목
  thumbnail:
    type: string
    nullable: true
    example: http://localhost:5001/static/uploads/image-1676914393377.png
  short_description:
    type: string
    nullable: true
    example: 아티클 설명
  content:
    type: string
    example: 아티클 내용
  my_views:
    type: integer
    example: 300
  created_at:
    type: string
    format: date-time
    example: 2023-02-21T07:54:39.312Z
  updated_at:
    type: string
    format: date-time
    example: 2023-02-21T07:54:39.312Z
  created_by_id:
    type: string
    format: uuid
    example: f1b00933-e51d-4f7f-bdf1-03016f3dd96b
