/auth/signup:
  post:
    tags:
      - auth
    summary: 회원가입
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
              nickname:
                type: string
    responses:
      201:
        description: 회원가입 성공
        content:
          application/json:
            schema:
              $ref: '../openapi.yaml#/components/schemas/User'

/auth/login:
  post:
    tags:
      - auth
    summary: 로그인
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
    responses:
      200:
        description: 로그인 성공
        content:
          application/json:
            schema:
              $ref: '../openapi.yaml#/components/schemas/User'
        headers:
          Set-Cookie:
            schema:
              type: string
              example: connect.sid=abcde12345;

/auth/logout:
  post:
    tags:
      - auth
    summary: 로그아웃
    responses:
      204:
        description: 로그아웃 성공
        headers:
          Set-Cookie:
            schema:
              type: string
              example: connect.sid=;
