/auth/login:
  post:
    tags:
      - auth
    summary: 로그인
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
    responses:
      '200':
        description: 로그인 성공
        content:
          application/json:
            schema:
              $ref: '../openapi.yaml#/components/schemas/User'
        headers:
          Set-Cookie:
            schema:
              type: string
              example: connect.sid=abcde12345
