/series:
  post:
    tags:
      - series
    summary: 시리즈 생성
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
    responses:
      201:
        description: 시리즈 생성 성공
        content:
          application/json:
            schema:
              $ref: '../openapi.yaml#/components/schemas/Series'
