/task:
  post:
    tags:
      - task
    summary: 태스크 생성
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              content:
                type: string
              date:
                type: string
                nullable: true
              time:
                type: string
                nullable: true
              task_card_id:
                type: integer
              parent_task_id:
                nullable: true
    responses:
      201:
        description: 태스크 생성 성공
        content:
          application/json:
            schema:
              $ref: '../openapi.yaml#/components/schemas/Task'

/task/{taskId}:
  patch:
    tags:
      - task
    summary: 태스크 수정
    parameters:
      - name: taskId
        in: path
        description: 수정할 태스크 id
        required: true
        schema:
          type: integer
          format: int64
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              content:
                type: string
              date:
                type: string
                nullable: true
              time:
                type: string
                nullable: true
              completed_at:
                type: string
                format: date-time
                nullable: true
              task_card_id:
                type: integer
              parent_task_id:
                nullable: true
    responses:
      200:
        description: 태스크 수정 성공
        content:
          application/json:
            schema:
              $ref: '../openapi.yaml#/components/schemas/Task'

  delete:
    tags:
      - task
    summary: 태스크 삭제
    parameters:
      - name: taskId
        in: path
        description: 수정할 태스크 id
        required: true
        schema:
          type: integer
          format: int64
    responses:
      204:
        description: 태스크 삭제 성공
