/user/me:
  get:
    tags:
      - user
    summary: 내 정보 조회
    responses:
      200:
        description: 내 정보 조회 성공
        content:
          application/json:
            schema:
              $ref: '../openapi.yaml#/components/schemas/User'
